# Generated by Django 4.2.16 on 2024-10-29 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "exerciseHabitsRecord",
            "0003_remove_user_groups_remove_user_is_superuser_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="user_id",
        ),
        migrations.AddField(
            model_name="exercise",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
