# Generated by Django 4.2.16 on 2024-10-29 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        (
            "exerciseHabitsRecord",
            "0004_remove_exercise_user_id_exercise_user_delete_user",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="exercise",
            name="user",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="利用者",
            ),
        ),
    ]
